DROP TABLE CATEGORIE;
CREATE TABLE CATEGORIE
(cat_code VARCHAR(3) NOT NULL,
cat_libelle VARCHAR(50),
CONSTRAINT PK_CAT PRIMARY KEY(cat_code)
)ENGINE=innodb;

DROP TABLE PRODUIT;
CREATE TABLE PRODUIT
(pdt_ref VARCHAR(3) NOT NULL,
pdt_designation VARCHAR(50),
pdt_prix DECIMAL(5,2),
pdt_image VARCHAR(50),
pdt_categorie VARCHAR(3),
CONSTRAINT Pk_PROD PRIMARY KEY(pdt_ref)
)ENGINE=innodb;

DROP TABLE PANIER;
CREATE TABLE PANIER
(pdt_ref VARCHAR(3)NOT NULL,
quantite INT(3) NOT NULL,
CONSTRAINT Pk_PAN PRIMARY KEY(pdt_ref)
)ENGINE=innodb;